### ISSUE TITLE
我认为你混淆了text2video和audio2face两个课题

### ISSUE THREAD

**Issue by ykk648** [jianzhnie/awesome-text-to-video#2]

**Comment by jianzhnie** [comment]
具体哪里出错了，可以指出来吗

**Comment by ykk648** [comment]
类似runway sd的才是text2video，类似deepbrain synthesia 或者你没写的Heygen， 本质上都是talking head的方式制造数字人，text2audio2face，技术路线是TTS+GAN

**Comment by jianzhnie** [comment]
非常感谢你的建议，我重新整理一下分类

**Comment by ykk648** [comment]
一点个人看法
